#!/bin/bash

inst_rules "$moddir/69-anti-evil-maid.rules"
inst "$moddir"/anti-evil-maid.sh /sbin/anti-evil-maid
inst "$moddir"/cryptroot-ask.antievilmaid /sbin/cryptroot-ask.antievilmaid
inst_hook cmdline 90 "$moddir/parse-anti-evil-maid.sh"

# TPM software stack
inst tpm_unsealdata
inst tpm_version
inst tcsd

# all this crap below is needed for tcsd to start properly...
inst ifconfig
inst "$moddir"/hosts /etc/hosts
inst "$moddir"/passwd /etc/passwd
inst "$moddir"/shadow /etc/shadow


