#!/bin/sh

log() {
    echo "${0##*/}: $1" >&2
}


log "detecting whether SRK is password protected"

if tpm_sealdata -z </dev/null >/dev/null; then
    log "no, SRK isn't password protected"
    echo -z
else
    log "yes, SRK is password protected; resetting dictionary attack lock..."
    tpm_resetdalock -z || true  # -z is an empty owner (not SRK) password
fi
