#!/bin/bash
set -e -o pipefail

firstluksuuid() {
    for param in $(cat /proc/cmdline); do
       case "$param" in rd.luks.uuid=*|rd_LUKS_UUID=*)
           echo "${param##*luks-}"
           return 0
       esac
    done
    return 1
}

topdev() {
    lsblk -snr -o "$1" "$2" | tail -n 1
}

if [ $# != 1 -a $# != 2 ] ; then
    echo "usage: ${0##*/} <dev> [<mnt>]" 2>&1
    exit 1
fi

case $(${2:+cat "$2"/anti-evil-maid/removable} 2>/dev/null) in
    0) exit 1 ;;
    1) exit 0 ;;
esac

firstluks=/dev/disk/by-uuid/$(firstluksuuid)
firstluks_disk_kname=$(topdev KNAME "$firstluks")

aem_disk=$(topdev KNAME,RM "$1")
aem_disk_kname=${aem_disk%% *}
aem_disk_rm=${aem_disk##* }

[ "$aem_disk_rm" = 1 -a "$aem_disk_kname" != "$firstluks_disk_kname" ]
