name: Test build and package QubesOS RPMs

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-package.yml@master
    with:
      base-commit: '62819a6fdf58d3d3c47aff5096dea9fb88ce1d53'
      patch-start: 0000
      qubes-component: 'antievilmaid'
      spec-pattern: '/^Source0:/'
      spec-file: 'anti-evil-maid'
