name: Test build and package QubesOS RPMs

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-packagev2.yml@aem-build-no-patches
    with:
      qubes-component: 'antievilmaid'
      git-url: ${{ github.repository }}
